title: Allison Morgan
author:
  name: Allison Morgan
  email: allimorgan98@gmail.com
description: >
  UX researcher | 


show_excerpts: false # set to true to show excerpts on the homepage
permalink: /:title


url: "https://allimorgan98-cloud.github.io"
baseurl: "/portfolio"


plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

collections:
  publication:
    output: true

theme: minima
