url: "https://allimorgan98-cloud.github.io"
#baseurl: "/portfolio"   # because your repo name is 'portfolio'

title: "Allison Morgan"
description: "UX / HMI Researcher"
author:
  name: "Allison Morgan"
  email: "allimorgan98@gmail.com"
  url: "https://allimorgan98-cloud.github.io/portfolio"

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

collections:
  publication:
    output: true
    permalink: /publication/:slug/

theme: minima
