project:
  - title: Conversational AI Coach for Performance Driving
    image: conversational-coach.jpg
    detail: >
      <p>Mixed-methods evaluation of a <b>dialog-based in-vehicle coach</b> vs. dashboard feedback. Ran simulator and in-vehicle studies, synchronized eye-tracking, physiological, and performance signals, and delivered decision-ready readouts that informed coaching flow changes.</p>

      <img src='site.baseurl/assets/images/project_detail/conversational-coach.jpg' class='modal-image-responsive' alt='Conversational coach keyscreen'>

      <hr>

      <p><span style="font-weight: 300">[My role]</span><br>Lead UXR — study design, instrumentation QA, analysis, stakeholder readout</p>
    tags:
      - <i class='fas fa-book'></i>&nbsp; AutomotiveUI ’25
      - HMI
      - Mixed-methods
    description: >-
      Dialog-based coaching vs. dashboards: evaluation and design implications
    id: conversational-coach

  - title: Computational Teaching via Multi-Task Imitation Learning
    image: icra-mtil.jpg
    detail: >
      <p>Built reliable <b>capture and evaluation pipelines</b> supporting multi-task imitation learning for driving skills. Standardized time-sync across simulator I/O, eye-tracking, and physio; defined user-centered success metrics in partnership with engineering.</p>

      <img src='site.baseurl/assets/images/project_detail/icra-mtil.jpg' class='modal-image-responsive' alt='ICRA project schematic'>

      <hr>

      <p><span style="font-weight: 300">[My role]</span><br>UXR & data quality lead — instrumentation, metrics, analysis</p>
    tags:
      - <i class='fas fa-book'></i>&nbsp; ICRA ’25
      - Data pipeline
      - Evaluation
    description: >-
      Time-synced multimodal capture and user-centered evaluation for IL
    id: icra-mtil

  - title: Task Decomposition for Learning Advanced Driving Skills
    image: acc-task-decomp.jpg
    detail: >
      <p>Studied <b>hierarchical task decomposition</b> to structure learning of complex performance-driving behaviors; informed training sequence and evaluation measures for coaching.</p>

      <img src='site.baseurl/assets/images/project_detail/acc-task-decomp.jpg' class='modal-image-responsive' alt='Task decomposition concept'>

      <hr>

      <p><span style="font-weight: 300">[My role]</span><br>Study design & analysis — protocol, metrics, synthesis</p>
    tags:
      - <i class='fas fa-book'></i>&nbsp; ACC ’25
      - Skill learning
      - Experiment design
    description: >-
      Structuring complex skills with hierarchical decomposition
    id: acc-task-decomposition

  - title: Gliding on Simulated Ice — Low-μ Drift Training
    image: low-mu-drift.jpg
    detail: >
      <p>Evaluated simulated low-friction (<b>low-μ</b>) environments for drift training; analyzed learning and transfer in a controlled simulator study and informed HMI safety cues.</p>

      <img src='site.baseurl/assets/images/project_detail/low-mu-drift.jpg' class='modal-image-responsive' alt='Low-mu drift training'>

      <hr>

      <p><span style="font-weight: 300">[My role]</span><br>Study design, instrumentation, data analysis</p>
    tags:
      - <i class='fas fa-book'></i>&nbsp; AutomotiveUI ’24
      - Simulator
      - HMI
    description: >-
      Does simulated low-μ improve drift training and transfer?
    id: low-mu-drift

  - title: Personalizing Driver Safety Interfaces
    image: cognitive-factors.jpg
    detail: >
      <p>Linked inferred <b>cognitive factors</b> to driving outcomes to personalize safety HMI. Contributed to mixed-methods analysis and measurable interface recommendations.</p>

      <img src='site.baseurl/assets/images/project_detail/cognitive-factors.jpg' class='modal-image-responsive' alt='Personalization framework'>

      <hr>

      <p><span style="font-weight: 300">[My role]</span><br>Measures design, analysis, recommendations</p>
    tags:
      - <i class='fas fa-book'></i>&nbsp; Scientific Reports ’24
      - Personalization
      - Human Factors
    description: >-
      From cognitive factors to personalized safety interfaces
    id: sci-rep-cognitive-factors

  - title: HMIway-env — Human–AI Teaming Simulation
    image: hmiway-env.jpg
    detail: >
      <p>Simulation framework modeling <b>driver behaviors and preferences</b> to test human–AI teaming strategies and HMI interventions.</p>

      <img src='site.baseurl/assets/images/project_detail/hmiway-env.jpg' class='modal-image-responsive' alt='HMIway-env schematic'>

      <hr>

      <p><span style="font-weight: 300">[My role]</span><br>UXR support — experimental scenarios, study measures, reporting</p>
    tags:
      - <i class='fas fa-book'></i>&nbsp; CVPR ’22
      - Simulation
      - Human–AI teaming
    description: >-
      Simulating behaviors/preferences to evaluate teaming & HMI
    id: hmiway-env

  - title: Skill Representation for Coaching
    image: skill-representation.jpg
    detail: >
      <p>Proposed a <b>data-driven schema</b> to represent driving skills from multimodal traces, enabling analysis, feedback, and coaching policies.</p>

      <img src='site.baseurl/assets/images/project_detail/skill-representation.jpg' class='modal-image-responsive' alt='Skill representation concept'>

      <hr>

      <p><span style="font-weight: 300">[My role]</span><br>Co-author — framing, analysis, narrative</p>
    tags:
      - <i class='fas fa-book'></i>&nbsp; HRI ’25 Workshop
      - Representation
      - Coaching
    description: >-
      A schema for representing skills from multimodal traces
    id: hri-skill-representation

  - title: MeTime — Personalized Streaming Discovery
    image: metime-cover.jpg
    detail: >
      <p>UCSD app concept to <b>cut time-to-decision</b> for busy streamers. Designed flows and hi-fi prototype with Karam: <b>Taste Curation</b> (quick preference quiz), <b>Randomizer</b> (one-tap play), <b>Tags search</b>, and <b>Saved-content filter</b>.</p>

      <img src='site.baseurl/assets/images/project_detail/metime-home.jpg' class='modal-image-responsive' alt='MeTime home screen'>

      <p style='text-align: center; font-weight: 300;'>Home · Tags · Randomizer · Taste Curation</p>

      <hr>

      <p><span style="font-weight: 300">[My role]</span><br>Co-designer — research, IA, flows, hi-fi prototype</p>
    tags:
      - UCSD
      - Product design
      - Prototype
    description: >-
      Faster, more relevant streaming discovery for time-pressed users
    id: metime
